services:
  database:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: verySecretPassword
      POSTGRES_USER: administrator
      POSTGRES_DB: todo
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U administrator -d todo"]
      interval: 10s
      retries: 6
      start_period: 30s
      timeout: 10s
  app:
    build: .
    restart: always
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql:\
        //administrator:verySecretPassword@database:5432/todo"
    ports:
      - "6400:6400"
    depends_on:
      database:
        condition: service_healthy
        restart: true
